// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _DBC;

#nullable disable

namespace _StudioShinWeb.Migrations
{
    [DbContext(typeof(DataBase))]
    [Migration("20220719061940_~shinip")]
    partial class shinip
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_oBjects.shinIps2", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"), 1L, 1);

                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IpType")
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("countCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("countName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("seenDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("state")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stateABR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("timesSeenCount")
                        .HasColumnType("bigint");

                    b.Property<int?>("timesSeenDay")
                        .HasColumnType("int");

                    b.Property<long?>("totalIpsSeen")
                        .HasColumnType("bigint");

                    b.Property<string>("zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("shinIps2");
                });

            modelBuilder.Entity("_oBjects.shinSiteMetrics", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("EventsFiredDebug")
                        .HasColumnType("int");

                    b.Property<int>("EventsFiredRelease")
                        .HasColumnType("int");

                    b.Property<int>("pageViewsDebug")
                        .HasColumnType("int");

                    b.Property<int>("pageViewsRelease")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("shinSiteMetrics");
                });
#pragma warning restore 612, 618
        }
    }
}
